server:
  port: 8766

spring:
  application:
    name: hystrix-consumer
  devtools:
    restart:
      enabled: true
eureka:
  instance:
    hostname: 192.168.88.128
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka
