server:
  port: 7963

spring:
  application:
    name: eureka-client

eureka:
  instance:
    lease-expiration-duration-in-seconds: 5
  client:
    service-url:
      defaultZone: http://192.168.88.128:8080/eureka/

