server:
  port: 7963

spring:
  application:
    name: eureka-client

eureka:
  instance:
    lease-expiration-duration-in-seconds: 5
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

